### ISSUE TITLE
Error getting the Request Token

### ISSUE THREAD

**Issue by abalonepaul** [CakePHP-Copula/Linkedin#6]
I am getting the following error from LinkedIn while trying to get the requestToken. 

oauth_problem=parameter_absent&oauth_parameters_absent=oauth_consumer_key%26oauth_signature_method%26oauth_signature%26oauth_timestamp%26oauth_nonce

It looks like we are sending a GET request and not sending the signature method, signature, timestamp, or nonce. 

The LinkedIn documentation says that they are expecting a POST request with the data sent as POST data. 

What is the best way to handle this?

Update: My bad. I reverted to another version and it is working fine.

**Comment by ProLoser** [comment]
Feel free to close bugs when you find they're invalid :)
