### ISSUE TITLE
Function not found

### ISSUE THREAD

**Issue by aCodeAlchemist** [CakePHP-Copula/Linkedin#7]
Call to undefined method OAuthClient::postRaw() 

LinkedinComponent.php line : 80

**Comment by ProLoser** [comment]
What line? What file? What code? You're giving me absolutely no useful information.

**Comment by ProLoser** [comment]
Honestly though this plugin uses an out-of-date version of the base plugin so it's not likely going to work anymore.

**Comment by aCodeAlchemist** [comment]
LinkedinComponent.php line : 80

**Comment by ProLoser** [comment]
There isn't a LinkedinComponent.

**Comment by aCodeAlchemist** [comment]
Ohh yes there is.
